# Generated by Django 3.2.5 on 2021-07-25 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.CharField(max_length=20, verbose_name='Культура')),
            ],
            options={
                'verbose_name': 'Культура',
                'verbose_name_plural': 'Культуры',
            },
        ),
        migrations.CreateModel(
            name='VegetationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climat_zone', models.CharField(max_length=50, verbose_name='Климатическая зона')),
                ('productivity', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Климатическая зона',
                'verbose_name_plural': 'Климатические зоны',
            },
        ),
        migrations.CreateModel(
            name='ElementsConcentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('phosphorus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('magnesium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sulfur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calcuim', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manganese', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('zinc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('copper', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('boron', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('molybdenum', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cobalt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('selenium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity_of_water', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('productivity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('climat_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.vegetationmode')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.culture')),
            ],
            options={
                'verbose_name': 'Данные из формы',
                'verbose_name_plural': 'Данные из формы',
            },
        ),
    ]
