# Generated by Django 3.2.5 on 2021-07-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='boron',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='calcuim',
            new_name='Ca',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='cobalt',
            new_name='Co',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='copper',
            new_name='Cu',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='iron',
            new_name='Fe',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='magnesium',
            new_name='K2O',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='manganese',
            new_name='Mg',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='molybdenum',
            new_name='Mn',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='nitrogen',
            new_name='Mo',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='phosphorus',
            new_name='N',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='potassium',
            new_name='PO4',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='selenium',
            new_name='S',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='sulfur',
            new_name='Se',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='zinc',
            new_name='Zn',
        ),
    ]
