# Generated by Django 3.2.5 on 2021-07-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20210727_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='PO4',
            new_name='P2O5',
        ),
    ]
