# Generated by Django 3.2.5 on 2021-08-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_rename_po4_elementsconcentration_p2o5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productivity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Урожайность')),
            ],
            options={
                'verbose_name': 'Урожайность',
                'verbose_name_plural': 'Урожайность',
            },
        ),
        migrations.RemoveField(
            model_name='vegetationmode',
            name='productivity',
        ),
    ]
