# Generated by Django 3.2.5 on 2021-08-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_auto_20210806_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivity',
            name='climat_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.vegetationmode'),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='climat_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.vegetationmode'),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.culture'),
        ),
        migrations.AlterField(
            model_name='vegetationmode',
            name='climat_zone',
            field=models.CharField(default='', max_length=50, verbose_name='Климатическая зона'),
        ),
    ]
