# Generated by Django 3.2.5 on 2021-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_auto_20210806_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultElementsConcentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.DecimalField(decimal_places=2, max_digits=5)),
                ('P2O5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('K2O', models.DecimalField(decimal_places=2, max_digits=5)),
                ('MgO', models.DecimalField(decimal_places=2, max_digits=5)),
                ('S', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Ca', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Fe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Mn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Zn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Cu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('B', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Mo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Co', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Se', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Содержание элементов по умолчанию',
                'verbose_name_plural': 'Содержание элементов по умолчанию',
            },
        ),
    ]
