# Generated by Django 3.2.5 on 2021-08-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_rename_mgo_defaultelementsconcentration_mg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultelementsconcentration',
            old_name='K2O',
            new_name='K',
        ),
        migrations.RenameField(
            model_name='defaultelementsconcentration',
            old_name='P2O5',
            new_name='P',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='K2O',
            new_name='K',
        ),
        migrations.RenameField(
            model_name='elementsconcentration',
            old_name='P2O5',
            new_name='P',
        ),
    ]
