# Generated by Django 3.2.5 on 2021-08-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_auto_20210821_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.TextField()),
                ('P', models.TextField()),
                ('K', models.TextField()),
                ('Mg', models.TextField()),
                ('S', models.TextField()),
                ('Ca', models.TextField()),
                ('Fe', models.TextField()),
                ('Mn', models.TextField()),
                ('Zn', models.TextField()),
                ('Cu', models.TextField()),
                ('B', models.TextField()),
                ('Mo', models.TextField()),
                ('Co', models.TextField()),
                ('Se', models.TextField()),
            ],
            options={
                'verbose_name': 'Описание элементов',
                'verbose_name_plural': 'Описание элементов',
            },
        ),
    ]
