# Generated by Django 3.2.5 on 2021-08-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_auto_20210825_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Ni',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True),
        ),
    ]
