# Generated by Django 3.2.5 on 2021-08-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_auto_20210825_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='B',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Ca',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Co',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Cu',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Fe',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='K',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Mg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Mn',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Mo',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='N',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Ni',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='P',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='S',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Se',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='defaultelementsconcentration',
            name='Zn',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='B',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='Ca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='Co',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='Cu',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='Fe',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='K',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='Mg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='Mn',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='Mo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='N',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='Ni',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='P',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='S',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='Se',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='elementsconcentration',
            name='Zn',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
