# Generated by Django 3.2.5 on 2021-07-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultElementsConcentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phosphorus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('magnesium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sulfur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calcuim', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iron', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manganese', models.DecimalField(decimal_places=2, max_digits=5)),
                ('zinc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('copper', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boron', models.DecimalField(decimal_places=2, max_digits=5)),
                ('molybdenum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cobalt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selenium', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Содержание элементов по умолчанию',
                'verbose_name_plural': 'Содержание элементов по умолчанию',
            },
        ),
        migrations.CreateModel(
            name='ElementsConsuption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.CharField(max_length=20, verbose_name='Культура')),
                ('nitrogen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phosphorus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('magnesium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sulfur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calcuim', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iron', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manganese', models.DecimalField(decimal_places=2, max_digits=5)),
                ('zinc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('copper', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boron', models.DecimalField(decimal_places=2, max_digits=5)),
                ('molybdenum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cobalt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selenium', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Вынос элементов',
                'verbose_name_plural': 'Вынос элементов',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_img', models.ImageField(upload_to='graphs')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
    ]
