# Generated by Django 3.2.5 on 2021-07-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20210727_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultelementsconcentration',
            old_name='PO4',
            new_name='P2O5',
        ),
        migrations.RenameField(
            model_name='elementsconsuption',
            old_name='PO4',
            new_name='P2O5',
        ),
    ]
