# Generated by Django 3.2.5 on 2021-08-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20210727_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultElementsConcentration',
        ),
    ]
